import React from 'react'
import Head from 'next/head'
import Slider from '../components/slider/Slider'
import Container from '@/layout/Container'
import { Title } from '@/components/interface/Title'
import Link from 'next/link'
import SquareCar from '@/components/interface/cards/SquareCar'
import { Grid06 } from '@/layout/Grid'
import Image from 'next/image'
// import { getSlides } from '@/functions/requests/slide/slideRequests'

import { FadeLoader } from 'react-spinners'
import CardCar from '@/components/interface/cards/CardCar'
import ProdutoRequest from '@/functions/requests/produto/produtoRequest'
import SlideRequests from '@/functions/requests/slide/slideRequests'

const categorias = [
  { nome: 'todos' },
  { nome: 'sedan' },
  { nome: 'hatch' },
  { nome: 'suv' },
  { nome: 'pick-up' },
  { nome: 'minivan' },
  { nome: 'esportivo' }
]

const requestCars = new ProdutoRequest(`/api/produtos`);
const requestSlides = new SlideRequests(`/api/sliders`)
// console.log(process.env.NEXT_API_URL)

export async function getServerSideProps() {
  const slides = await requestSlides.getRequest();
  const carros = await requestCars.getRequest();
  return {
    props: {
      slides,
      carros
    }
  }
}

export default function Home({slides, carros}:{slides:DataGridState[], carros:DataGridCar[]}) {
  
  const [_carros, setCarros] = React.useState<DataGridCar[]>(carros)
  const [active, setActive] = React.useState<string>('todos')  
  
                 
  const override = {
    display: 'block',
    margin: '200px auto',
    borderColor: 'red',
  }

  function Loading() {
    return (
      <div className="sweet-loading">
        <FadeLoader color={"#123abc"} loading={true} cssOverride={override}/>
      </div>
    );
  }

  function handleClick({currentTarget}:React.MouseEvent) {    
    if (currentTarget instanceof HTMLLIElement) {                
      setActive(currentTarget.innerText)
      if (carros) {
        if (currentTarget.innerText !== "todos") {          
          setCarros( () => carros.filter( (carro) => {
              return carro.categoria === currentTarget.innerText
            })
          )
        } else {
          setCarros(carros)
        }
      } else {
        console.log('error')
      }
    }
  }

  function render() {
    if(_carros){
      return _carros.map( (carro, index) => {        
        return (
          <CardCar
            src={carro.image as string}
            alt={`${carro.marca} - ${carro.modelo}`}
            ano={carro.ano} 
            key={index}            
            marca={carro.marca}
            modelo={carro.modelo}
            href={`/${carro.id}`}            
          />
        )
      })
    } else {
      return <div>{Loading()}</div>
    }
  }
  
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />        
      </Head>

      {(slides)? <Slider slides={slides}/> : <div>{Loading()}</div>}
      
      <div style={{height: '100vh'}}>        
        <section>
          <div className="title-catalogo">
            <span>Escolha a categoria</span>
          </div>
          <div>
            <ul className='categoria-btn'>
              {categorias.map( (categoria, index) => {
                return (
                  <li 
                  key={index} 
                  className={(categoria.nome === active) ? "active" : ""}
                  onClick={handleClick}                  
                  >
                    <span>{categoria.nome}</span>
                  </li>
                )
              })}
            </ul>
          </div>
        </section>
        <section>
          <Container className="wrap">
            {render()}
          </Container>
        </section>
      </div>
    </>
  )  
}
